openapi: 3.0.0
info:
  title: WatchGator API
  description: Movies / Series fast and reliable search engine
  version: 1.0.0
servers:
  - url: https://watchgator-server.herokuapp.com/api
    description: Main endpoint

path:
  /movies/all/{page?}:
    parameters:
      - in: path
        name: page
        schema:
          type: integer
        description: The chunk index to display
    get:
      summary: Get the {page} (default 1) chunk containing 20 movies
      tags: [Movies]
      responses:
        "200":
          description: List of all movies for page n.{page}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoviesResponse'
  /movies/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: The movie id
    get:
      summary: Get the movie with the id {id}
      tags: [Movies]
      responses:
        "200":
          description: Get the {id} movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /movies/find:
    post:
      summary: Find Movies by key
      tags: [Movies]
      requestBody:
        description: Any Movie key to search on, except arrays (actors, genres, directors)
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieFind'
      responses:
        "200":
          description: Find movies by searching (case-insensitive RegExp) with specified body keys
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoviesResponse'

components:
 schemas:
   MoviesResponse:
     type: object
     properties:
       time:
         type: int
         description: time (in ms) taken by the request
       total:
         type: int
         description: total items number
       totalPages:
         type: int
         description: total of pages
       page:
         type: int
         description: current page returned
       pageResults:
         type: int
         description: total of result in the current page
       results:
         type: array
         description: results
         items:
           $ref: '#/components/schemas/MoviesChunk'
         minItems: 1
         maxItems: 20
     example:
       total: 274500,
       totalPages: 13725,
       page: 1,
       totalResults: 20,
       results: [
        {
            _id: "tt8936646",
            title: "Tyler Rake",
            year: 2020,
            rating: 6,
            nbRatings: 84858,
            metaScore: 56,
            runtime: 116,
            genres: [
                {
                    name: "Action"
                },
                {
                    name: "Thriller"
                }
            ],
            directors: [
                {
                    id: "nm1092087",
                    name: "Sam Hargrave"
                }
            ],
            actors: [
                {
                    id: "nm1165110",
                    name: "Chris Hemsworth"
                },
                {
                    id: "nm11523062",
                    name: "Bryon Lerum"
                },
                {
                    id: "nm11523063",
                    name: "Ryder Lerum"
                },
                {
                    id: "nm7287299",
                    name: "Rudhraksh Jaiswal"
                }
            ],
            gross: null
        }
      ]


   MoviesList:
     type: array
     items:
       $ref: '#/components/schemas/MoviesChunk'
     uniqueItems: true

   MoviesChunk:
     type: array
     items:
       $ref: '#/components/schemas/Movie'
     minItems: 1
     maxItems: 20
     uniqueItems: true

   MovieFind:
     type: object
     properties:
       key:
         type: string | int | float
       matchCase:
         type: bool
     example:
       title: "paras"
       matchCase: false

   Movie:
     type: object
     properties:
       _id:
         type: string
         description: Movie's ID
       title:
         type: string
         description: title of the movie
       year:
         type: int
         description: year of release
       rating:
         type: float
         description: IMDB rating
       nbRatings:
         type: int
         description: number of ppl that rated the movie
       metaScore:
         type: int
         description: IMDB popularity score
       certificate:
         type: string
         description: for which public is addressed the movie
       runtime:
         type: int
         description: duration of the movie
       genre:
         type: array
         description: category(ies) of the movie
       description:
         type: string
         description: short synopsis
       picture:
         type: string
         description: picture URL
       directors:
         type: array
         description: main director name
       actors:
         type: array
         description: list of the actors
       gross:
         type: string
         description: total budget of the movie
     example:
       _id: "tt6751668"
       title: "Parasite"
       year: 2019
       rating: 8.6
       nbRatings: 382763
       metaScore: 96
       certificate: "R"
       runtime: 132
       genre: [
        {
          name: "Action"
        },
        {
          name: "Thriller"
        }
       ]
       description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan."
       picture: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@.jpg"
       directors: [
        {
          id: "nm1092087",
          name: "Sam Hargrave"
        }
       ]
       actors": [
        {
          id: "nm1165110",
          name: "Chris Hemsworth"
        },
        {
          id: "nm0267042",
          name: "Golshifteh Farahani"
        },
        {
          id: "nm7287299",
          name: "Rudhraksh Jaiswal"
        },
        {
          id: "nm2534972",
          name: "Shivam Vichare"
        }
       ]
       gross: "$53.37M"
